export const ED_TAB_META = {
  overview: { label: 'Overview', icon: 'grid' },
  requisitions: { label: 'Requisitions', icon: 'cart', openLink: '/dashboard/requisitions', openLabel: 'Open Requisitions Module' },
  special_requisitions: { label: 'Vehicle Utilization', icon: 'truck', openLink: '/dashboard/special-requisitions', openLabel: 'Open Vehicle Utilization Module' },
  leave_requests: { label: 'Leave Requests', icon: 'calendar', openLink: '/dashboard/leave-requests', openLabel: 'Open Leave Requests Module' },
  leave_schedule: { label: 'Leave Schedule', icon: 'calendar', openLink: '/dashboard/leave-schedule', openLabel: 'Open Leave Schedule Module' },
  missions: { label: 'Missions', icon: 'map', openLink: '/dashboard/missions', openLabel: 'Open Missions Module' },
  documents: { label: 'Documents', icon: 'files', openLink: '/dashboard/documents', openLabel: 'Open Documents Module' },
  reports: { label: 'Staff Reports', icon: 'file', openLink: '/dashboard/reports', openLabel: 'Open Staff Reports Module' },
  membership_reports: { label: 'Membership Reports', icon: 'chart', openLink: '/dashboard/membership-reports', openLabel: 'Open Membership Reports Module' },
  tickets: { label: 'Open Tickets', icon: 'ticket', openLink: '/dashboard/tickets', openLabel: 'Open Tickets Module' },
  todos: { label: 'Todos', icon: 'list', openLink: '/dashboard/todos', openLabel: 'Open Todos Module' },
  communications: { label: 'Communications', icon: 'chat', openLink: '/dashboard/communications', openLabel: 'Open Communications Module' },
  assets: { label: 'Assets', icon: 'tool', openLink: '/dashboard/assets', openLabel: 'Open Assets Module' },
  attendance: { label: 'Attendance', icon: 'check', openLink: '/dashboard/attendance', openLabel: 'Open Attendance Module' },
  permissions: { label: 'Permissions', icon: 'shield', openLink: '/dashboard/permissions', openLabel: 'Open Permissions Module' },
  users: { label: 'Users / Staff', icon: 'users', openLink: '/dashboard/users', openLabel: 'My Account / Profile' },
  inventory: { label: 'Inventory', icon: 'box', openLink: '/dashboard/inventory', openLabel: 'Open Inventory Module' },
  members: { label: 'Members', icon: 'users', openLink: '/dashboard/members', openLabel: 'Open Members Module' },
};

export const ED_MODULE_GROUPS = {
  'Operations & Reports': [
    'requisitions', 'special_requisitions', 'leave_requests', 'leave_schedule', 'missions',
    'documents', 'reports', 'membership_reports', 'members',
  ],
  'General & Administration': [
    'tickets', 'todos', 'communications', 'assets', 'inventory',
    'attendance', 'permissions', 'users',
  ],
};

export const ED_RECORD_LINKS = {
  requisitions: (id) => `/dashboard/requisitions/${id}`,
  special_requisitions: (id) => `/dashboard/special-requisitions/${id}`,
  leave_requests: (id) => `/dashboard/leave-requests/${id}`,
  leave_schedule: (id) => `/dashboard/leave-schedule/${id}`,
  missions: (id) => `/dashboard/missions/${id}`,
  documents: (id) => `/dashboard/documents/${id}`,
  reports: (id) => `/dashboard/reports/${id}`,
  membership_reports: (id) => `/dashboard/membership-reports/${id}`,
  tickets: (id) => `/dashboard/tickets/${id}`,
  todos: (id) => `/dashboard/todos/${id}`,
  communications: (id) => `/dashboard/communications/${id}`,
  permissions: (id) => `/dashboard/permissions/${id}`,
  assets: (id) => `/dashboard/assets?asset=${id}`,
  attendance: (id) => `/dashboard/attendance/${id}`,
  users: () => '/dashboard/profile',
  inventory: () => '/dashboard/inventory',
  members: (id) => `/dashboard/members/${id}`,
};

export const ED_MODULE_COLUMNS = {
  requisitions: [
    { key: 'date', label: 'Date', format: 'date' },
    { key: 'department_name', label: 'Department' },
    { key: 'prepared_by_name', label: 'Prepared By' },
    { key: 'total_amount_requested', label: 'Amount', format: 'money' },
    { key: 'status', label: 'Status', format: 'status' },
    { key: 'authorized_by', label: 'ED Auth', format: 'ed_auth' },
  ],
  special_requisitions: [
    { key: 'title', label: 'Title' },
    { key: 'type', label: 'Type', format: 'vehicle_type' },
    { key: 'department_name', label: 'Department' },
    { key: 'prepared_by_name', label: 'Prepared By' },
    { key: 'start_time', label: 'Start', format: 'datetime' },
    { key: 'status', label: 'Status', format: 'status' },
    { key: 'authorized_by', label: 'ED Auth', format: 'ed_auth' },
  ],
  leave_requests: [
    { key: 'applicant_name', label: 'Applicant', subKey: 'applicant_role' },
    { key: 'leave_type', label: 'Type' },
    { key: 'leave_from', label: 'Period', format: 'period', endKey: 'return_date' },
    { key: 'requested_days', label: 'Days' },
    { key: 'hr_verification_status', label: 'HR', format: 'status' },
    { key: 'leave_requests_status', label: 'Status', format: 'status' },
  ],
  leave_schedule: [
    { key: 'employee_name', label: 'Employee' },
    { key: 'from_date', label: 'Period', format: 'period', endKey: 'return_date' },
    { key: 'status', label: 'Status', format: 'status' },
    { key: 'hr_read_status', label: 'HR Read', format: 'read_hr' },
    { key: 'ed_read_status', label: 'ED Read', format: 'read_ed' },
  ],
  missions: [
    { key: 'applicant_name', label: 'Applicant' },
    { key: 'destination', label: 'Destination' },
    { key: 'departure_date', label: 'Departure', format: 'date' },
    { key: 'return_date', label: 'Return', format: 'date' },
    { key: 'days_requested', label: 'Days' },
    { key: 'hr_verification_status', label: 'HR', format: 'status' },
    { key: 'mission_requests_status', label: 'Status', format: 'status' },
  ],
  documents: [
    { key: 'title', label: 'Title' },
    { key: 'type', label: 'Type' },
    { key: 'file_type', label: 'File Type' },
    { key: 'creator_name', label: 'Creator' },
    { key: 'share_count', label: 'Shares' },
    { key: 'status', label: 'Status', format: 'status' },
  ],
  reports: [
    { key: 'title', label: 'Title' },
    { key: 'type', label: 'Type' },
    { key: 'period_start', label: 'Period', format: 'period', endKey: 'period_end' },
    { key: 'creator_name', label: 'Creator' },
    { key: 'comment_count', label: 'Comments' },
  ],
  membership_reports: [
    { key: 'title', label: 'Title' },
    { key: 'report_type', label: 'Type' },
    { key: 'location', label: 'Location' },
    { key: 'start_date', label: 'Period', format: 'period', endKey: 'end_date' },
    { key: 'creator_name', label: 'Creator' },
    { key: 'status', label: 'Status', format: 'status' },
  ],
  tickets: [
    { key: 'title', label: 'Title' },
    { key: 'created_by_name', label: 'Created By' },
    { key: 'assigned_to_name', label: 'Assigned To', empty: 'Unassigned' },
    { key: 'category', label: 'Category' },
    { key: 'priority', label: 'Priority', format: 'status' },
    { key: 'status', label: 'Status', format: 'status' },
    { key: 'created_at', label: 'Created', format: 'date' },
  ],
  todos: [
    { key: 'title', label: 'Title' },
    { key: 'owner_name', label: 'Owner' },
    { key: 'priority', label: 'Priority', format: 'status' },
    { key: 'due_date', label: 'Due', format: 'date' },
    { key: 'is_completed', label: 'Done', format: 'bool' },
  ],
  communications: [
    { key: 'title', label: 'Title' },
    { key: 'creator_name', label: 'Creator' },
    { key: 'start_time', label: 'Start', format: 'datetime' },
    { key: 'end_time', label: 'End', format: 'datetime' },
  ],
  permissions: [
    { key: 'title', label: 'Title' },
    { key: 'creator_name', label: 'Creator' },
    { key: 'start_time', label: 'Start', format: 'datetime' },
    { key: 'end_time', label: 'End', format: 'datetime' },
  ],
  assets: [
    { key: 'name', label: 'Name' },
    { key: 'serial_number', label: 'Serial #' },
    { key: 'label_number', label: 'Label #' },
    { key: 'location', label: 'Location', format: 'status' },
    { key: 'status', label: 'Status', format: 'status' },
    { key: 'assigned_to_name', label: 'Assigned To' },
  ],
  attendance: [
    { key: 'title', label: 'Title' },
    { key: 'type', label: 'Type' },
    { key: 'location', label: 'Location' },
    { key: 'attendance_date', label: 'Date', format: 'date' },
    { key: 'signed_count', label: 'Signed', format: 'attendance_signed', totalKey: 'total_invited' },
    { key: 'status', label: 'Status', format: 'status' },
  ],
  users: [
    { key: 'names', label: 'Name' },
    { key: 'email', label: 'Email' },
    { key: 'phone', label: 'Phone' },
    { key: 'role', label: 'Role' },
    { key: 'department_name', label: 'Department' },
    { key: 'active', label: 'Active', format: 'bool' },
  ],
  inventory: [
    { key: 'name', label: 'Item' },
    { key: 'category', label: 'Category' },
    { key: 'current_quantity', label: 'Stock' },
    { key: 'unit', label: 'Unit' },
    { key: 'min_stock', label: 'Min Level' },
    { key: 'created_by_name', label: 'Created By' },
  ],
  members: [
    { key: 'company_name', label: 'Company' },
    { key: 'owner_name', label: 'Owner' },
    { key: 'membership_status', label: 'Status', format: 'status' },
    { key: 'membership_category', label: 'Category' },
    { key: 'category_name', label: 'Platform Category' },
    { key: 'province', label: 'Province' },
    { key: 'district', label: 'District' },
  ],
};
